from typing import Dict, Tuple

def get_app(dbg: int) -> str: ...
def suspend_thread(dbg: int,thread_id: int) -> bool: ...
def resume_thread(dbg: int,thread_id: int) -> bool: ...
def allocate_mem(dbg: int,size: int,allocation_type: int,protect: int) -> Tuple[bool, int]: ...
def free_mem(dbg: int,address: int,size: int,free_type: int) -> bool: ...
def create_thread(dbg: int,address: int,params: int,creation_flags: int) -> Tuple[int, int]: ...
def read_mem(dbg: int,address: int,buffer:bytearray) -> Tuple[bool, int]: ...
def write_mem(dbg: int,address: int,buffer:bytearray) -> Tuple[bool, int]: ...

def remove_bp(dbg: int,bp: Dict) -> bool: ...
def set_bp_one_time(dbg: int,bp: Dict,enabled: bool) -> bool: ...
def add_soft_bp(dbg: int,address: int) -> Tuple[bool, Dict]: ...
def add_hard_bp(dbg: int,address: int,access_type: int,size: int) -> Tuple[bool, Dict]: ...
def add_mem_bp(dbg: int,address: int,access_type: int,size: int) -> Tuple[bool, Dict]: ...

# 下面这四个将会帮助刷新VEH调试器信息
def get_iats(dbg: int) -> Dict[int,str]: ...
def get_threads(dbg: int) -> list: ...
def virtual_query(dbg: int) -> list: ...
def get_modules(dbg: int) -> Dict[str,Dict]: ...